[tools]
bun = "latest"
snyk = "latest"
fzf = "latest"
jq = "latest"
kubectx = "latest"
node = "latest"
stern = "latest"
go = "latest"
kubectl = "latest"
ghq = "latest"
yarn = "latest"
pre-commit = "latest"
neovim = "latest"
java = "latest"
